import type { ChoreographySet } from './types';

/** Choreographies for events in the Evangelio era. */
const EVANGELIO: ChoreographySet = {
  // ANUNCIACIÓN — Gabriel desciende, María se inclina, Jesús emerge concebido.
  'anunciacion': {
    steps: [
      { pinIdx: 2, opacity: 0, scale: 0.3, duration: 0.001 },
      { pinIdx: 1, scale: 1, opacity: 1, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 0, offset: [0, -28], scale: 0.85, opacity: 0.6, duration: 0.001 },
      { pinIdx: 0, offset: [0, -10], scale: 0.95, opacity: 1, duration: 1.4, ease: 'power2.out' },
      { pinIdx: 1, offset: [0, 4], scale: 0.97, duration: 1.2, ease: 'sine.inOut' },
      { pinIdx: 0, offset: [0, 0], scale: 1, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 2, opacity: 0.4, scale: 0.55, duration: 1.4, ease: 'power2.out' },
      { pinIdx: 1, scale: 1.02, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 2, opacity: 1, scale: 1, duration: 1.6, ease: 'expo.out' },
      { pinIdx: 0, scale: 1.05, duration: 0.7, ease: 'sine.inOut' },
      { pinIdx: 1, offset: [0, 0], scale: 1, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 0, scale: 1, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 2, scale: 1, opacity: 1, duration: 0.6, ease: 'sine.inOut' },
    ],
  },

  // ASCENSIÓN — Jesús sube y se desvanece; Pedro y María miran hacia arriba.
  'ascension': {
    steps: [
      { pinIdx: 0, offset: [0, 0], scale: 1, opacity: 1, duration: 0.001 },
      { pinIdx: 1, scale: 1, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 2, scale: 1, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 0, scale: 1.1, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 0, offset: [0, -14], scale: 1.05, duration: 1.2, ease: 'power2.out' },
      { pinIdx: 1, offset: [0, 2], scale: 0.97, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 2, offset: [0, 3], scale: 0.96, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 0, offset: [0, -34], scale: 0.85, opacity: 0.7, duration: 1.4, ease: 'power2.out' },
      { pinIdx: 0, offset: [0, -60], scale: 0.65, opacity: 0.35, duration: 1.6, ease: 'power2.in' },
      { pinIdx: 1, scale: 0.94, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 2, scale: 0.94, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 0, offset: [0, -90], scale: 0.4, opacity: 0, duration: 1.6, ease: 'expo.in' },
      { pinIdx: 0, offset: [0, 0], scale: 1, opacity: 1, duration: 0.001 },
      { pinIdx: 1, offset: [0, 0], scale: 1, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 2, offset: [0, 0], scale: 1, duration: 0.8, ease: 'sine.inOut' },
    ],
  },

  // BAUTISMO — Jesús desciende al Jordán, Juan inclina, paloma pulsa.
  'bautismo-de-jesus': {
    steps: [
      { pinIdx: 0, offset: [0, 0], scale: 1, opacity: 1, duration: 0.001 },
      { pinIdx: 1, scale: 1, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 0, offset: [0, 6], scale: 0.96, duration: 1.2, ease: 'sine.inOut' },
      { pinIdx: 1, offset: [0, 3], scale: 0.97, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 0, offset: [0, 10], scale: 0.92, opacity: 0.85, duration: 1.0, ease: 'power2.in' },
      { pinIdx: 1, scale: 1, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 0, scale: 1.18, opacity: 1, duration: 0.9, ease: 'expo.out' },
      { pinIdx: 1, scale: 1.05, duration: 0.6, ease: 'sine.inOut' },
      { pinIdx: 0, scale: 1.25, duration: 0.6, ease: 'sine.inOut' },
      { pinIdx: 0, offset: [0, -4], scale: 1.1, duration: 1.0, ease: 'power2.out' },
      { pinIdx: 1, offset: [0, 0], scale: 1, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 0, offset: [0, 0], scale: 1, duration: 0.8, ease: 'sine.inOut' },
    ],
  },

  // CONVERSIÓN DE PABLO — rayo, caída, ceguera, bautismo, conversión brillante.
  'conversion-de-pablo': {
    steps: [
      { pinIdx: 0, offset: [0, 0], scale: 1, opacity: 1, duration: 0.001 },
      { pinIdx: 1, opacity: 0.3, scale: 0.85, duration: 0.001 },
      { pinIdx: 0, scale: 1.05, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 0, scale: 1.3, opacity: 1, duration: 0.4, ease: 'expo.out' },
      { pinIdx: 0, offset: [0, 18], scale: 0.7, opacity: 0.55, duration: 0.8, ease: 'power3.in' },
      { pinIdx: 0, offset: [0, 22], scale: 0.65, opacity: 0.4, duration: 1.2, ease: 'sine.inOut' },
      { pinIdx: 1, opacity: 0.7, scale: 0.95, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 1, offset: [-6, 0], opacity: 1, scale: 1, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 0, offset: [0, 12], scale: 0.8, opacity: 0.7, duration: 0.8, ease: 'sine.out' },
      { pinIdx: 1, scale: 1.05, duration: 0.6, ease: 'sine.inOut' },
      { pinIdx: 0, offset: [0, 0], scale: 1.1, opacity: 1, duration: 1.2, ease: 'power2.out' },
      { pinIdx: 0, scale: 1.15, duration: 0.6, ease: 'sine.inOut' },
      { pinIdx: 1, offset: [0, 0], scale: 1, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 0, scale: 1, duration: 0.8, ease: 'sine.inOut' },
    ],
  },

  // CRUCIFIXIÓN — Jesús se eleva, agoniza, se apaga; dolientes encogen.
  'crucifixion': {
    steps: [
      { pinIdx: 0, offset: [0, 0], scale: 1, opacity: 1, duration: 0.001 },
      { pinIdx: 1, scale: 1, opacity: 1, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 2, scale: 1, opacity: 1, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 3, scale: 1, opacity: 1, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 0, offset: [0, -6], scale: 1.05, duration: 1.2, ease: 'power2.out' },
      { pinIdx: 1, offset: [0, 4], scale: 0.95, opacity: 0.85, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 2, offset: [0, 4], scale: 0.95, opacity: 0.85, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 3, offset: [0, 4], scale: 0.95, opacity: 0.85, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 0, scale: 1.08, opacity: 0.95, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 0, scale: 0.95, opacity: 0.5, duration: 1.4, ease: 'power3.in' },
      { pinIdx: 1, offset: [0, 8], scale: 0.88, opacity: 0.65, duration: 1.2, ease: 'sine.inOut' },
      { pinIdx: 2, offset: [0, 8], scale: 0.88, opacity: 0.65, duration: 1.2, ease: 'sine.inOut' },
      { pinIdx: 3, offset: [0, 8], scale: 0.88, opacity: 0.65, duration: 1.2, ease: 'sine.inOut' },
      { pinIdx: 0, scale: 0.9, opacity: 0.15, duration: 1.6, ease: 'expo.in' },
      { pinIdx: 0, offset: [0, 0], scale: 1, opacity: 1, duration: 0.001 },
      { pinIdx: 1, offset: [0, 0], scale: 1, opacity: 1, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 2, offset: [0, 0], scale: 1, opacity: 1, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 3, offset: [0, 0], scale: 1, opacity: 1, duration: 0.8, ease: 'sine.inOut' },
    ],
  },

  // ELECCIÓN DE LOS DOCE — apóstoles emergen secuencialmente alrededor de Jesús.
  'eleccion-doce-apostoles': {
    steps: [
      { pinIdx: 1, opacity: 0, scale: 0.5, duration: 0.001 },
      { pinIdx: 2, opacity: 0, scale: 0.5, duration: 0.001 },
      { pinIdx: 3, opacity: 0, scale: 0.5, duration: 0.001 },
      { pinIdx: 4, opacity: 0, scale: 0.5, duration: 0.001 },
      { pinIdx: 5, opacity: 0, scale: 0.5, duration: 0.001 },
      { pinIdx: 0, scale: 1.1, duration: 0.8, ease: 'sine.out' },
      { pinIdx: 1, opacity: 1, scale: 1, duration: 0.7, ease: 'back.out(1.4)' },
      { pinIdx: 2, opacity: 1, scale: 1, duration: 0.7, ease: 'back.out(1.4)' },
      { pinIdx: 3, opacity: 1, scale: 1, duration: 0.7, ease: 'back.out(1.4)' },
      { pinIdx: 4, opacity: 1, scale: 1, duration: 0.7, ease: 'back.out(1.4)' },
      { pinIdx: 5, opacity: 0.85, scale: 0.95, duration: 0.7, ease: 'sine.out' },
      { pinIdx: 0, scale: 1.15, duration: 0.6, ease: 'sine.inOut' },
      { pinIdx: 5, opacity: 0.7, offset: [4, 0], duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 0, scale: 1, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 5, opacity: 1, offset: [0, 0], scale: 1, duration: 0.6, ease: 'sine.inOut' },
    ],
  },

  // ENTRADA TRIUNFAL — Jesús al frente, pulse triunfal, discípulos siguen.
  'entrada-triunfal-jerusalen': {
    steps: [
      { pinIdx: 0, offset: [0, 0], scale: 1, opacity: 1, duration: 0.001 },
      { pinIdx: 1, scale: 1, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 2, scale: 1, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 0, scale: 1.12, duration: 0.7, ease: 'sine.out' },
      { pinIdx: 0, scale: 1, duration: 0.5, ease: 'sine.in' },
      { pinIdx: 0, scale: 1.15, duration: 0.7, ease: 'sine.out' },
      { pinIdx: 1, scale: 1.06, duration: 0.5, ease: 'sine.inOut' },
      { pinIdx: 2, scale: 1.06, duration: 0.5, ease: 'sine.inOut' },
      { pinIdx: 0, scale: 1, duration: 0.5, ease: 'sine.in' },
      { pinIdx: 1, scale: 1, duration: 0.5, ease: 'sine.in' },
      { pinIdx: 2, scale: 1, duration: 0.5, ease: 'sine.in' },
      { pinIdx: 0, scale: 1.18, duration: 0.8, ease: 'sine.out' },
      { pinIdx: 0, scale: 1, duration: 0.6, ease: 'sine.inOut' },
    ],
  },

  // GETSEMANÍ — Jesús ora postrado, Pedro duerme, Judas se acerca traidor.
  'getsemani': {
    steps: [
      { pinIdx: 0, offset: [0, 0], scale: 1, opacity: 1, duration: 0.001 },
      { pinIdx: 1, scale: 1, opacity: 1, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 2, offset: [12, 0], opacity: 0.3, scale: 0.85, duration: 0.001 },
      { pinIdx: 0, offset: [0, 6], scale: 0.95, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 0, offset: [0, 10], scale: 0.92, opacity: 0.85, duration: 1.2, ease: 'power2.in' },
      { pinIdx: 1, scale: 0.95, opacity: 0.75, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 0, offset: [0, 12], scale: 0.9, opacity: 0.75, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 1, opacity: 0.5, scale: 0.92, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 2, offset: [8, 0], opacity: 0.5, scale: 0.9, duration: 1.2, ease: 'sine.inOut' },
      { pinIdx: 0, scale: 0.88, opacity: 0.7, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 2, offset: [3, 0], opacity: 0.8, scale: 0.95, duration: 1.0, ease: 'power2.in' },
      { pinIdx: 0, offset: [0, 8], scale: 0.94, opacity: 0.9, duration: 0.8, ease: 'sine.out' },
      { pinIdx: 2, offset: [0, 0], opacity: 1, scale: 1, duration: 0.6, ease: 'power2.out' },
      { pinIdx: 1, opacity: 1, scale: 1, duration: 0.6, ease: 'sine.inOut' },
      { pinIdx: 0, offset: [0, 0], scale: 1, opacity: 1, duration: 0.8, ease: 'sine.inOut' },
    ],
  },

  // HUIDA A EGIPTO — familia drift sur (right+down), magos se desvanecen, Herodes pulsa furioso.
  'huida-a-egipto': {
    steps: [
      { pinIdx: 0, offset: [0, 0], scale: 1, opacity: 1, duration: 0.001 },
      { pinIdx: 1, scale: 1, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 2, scale: 1, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 3, scale: 1, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 4, scale: 0.92, opacity: 0.7, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 5, scale: 0.92, opacity: 0.7, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 6, scale: 0.92, opacity: 0.7, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 3, scale: 1.18, duration: 0.7, ease: 'expo.out' },
      { pinIdx: 4, offset: [-6, -4], opacity: 0.25, scale: 0.7, duration: 1.0, ease: 'power2.in' },
      { pinIdx: 5, offset: [-6, -4], opacity: 0.25, scale: 0.7, duration: 1.0, ease: 'power2.in' },
      { pinIdx: 6, offset: [-6, -4], opacity: 0.25, scale: 0.7, duration: 1.0, ease: 'power2.in' },
      { pinIdx: 2, offset: [10, 6], scale: 0.95, duration: 1.4, ease: 'sine.inOut' },
      { pinIdx: 1, offset: [10, 6], scale: 0.95, duration: 1.4, ease: 'sine.inOut' },
      { pinIdx: 0, offset: [10, 6], scale: 0.9, duration: 1.4, ease: 'sine.inOut' },
      { pinIdx: 3, scale: 1.08, duration: 0.6, ease: 'sine.inOut' },
      { pinIdx: 0, offset: [0, 0], scale: 1, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 1, offset: [0, 0], scale: 1, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 2, offset: [0, 0], scale: 1, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 3, scale: 1, duration: 0.6, ease: 'sine.inOut' },
      { pinIdx: 4, offset: [0, 0], scale: 1, opacity: 1, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 5, offset: [0, 0], scale: 1, opacity: 1, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 6, offset: [0, 0], scale: 1, opacity: 1, duration: 0.8, ease: 'sine.inOut' },
    ],
  },

  // JESÚS 12 AÑOS — niño Jesús brilla en el templo, padres lo buscan y lo encuentran.
  'jesus-en-el-templo-12-anos': {
    steps: [
      { pinIdx: 0, offset: [0, 0], scale: 1, opacity: 1, duration: 0.001 },
      { pinIdx: 1, offset: [-14, 0], opacity: 0.5, scale: 0.9, duration: 0.001 },
      { pinIdx: 2, offset: [-14, 0], opacity: 0.5, scale: 0.9, duration: 0.001 },
      { pinIdx: 0, scale: 1.1, duration: 0.9, ease: 'sine.out' },
      { pinIdx: 0, scale: 1.18, opacity: 1, duration: 0.7, ease: 'expo.out' },
      { pinIdx: 0, scale: 1.05, duration: 0.7, ease: 'sine.inOut' },
      { pinIdx: 1, offset: [-6, 0], opacity: 0.7, scale: 0.95, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 2, offset: [-6, 0], opacity: 0.7, scale: 0.95, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 0, scale: 1.15, duration: 0.6, ease: 'sine.inOut' },
      { pinIdx: 1, offset: [0, 0], opacity: 1, scale: 1, duration: 1.0, ease: 'power2.out' },
      { pinIdx: 2, offset: [0, 0], opacity: 1, scale: 1, duration: 1.0, ease: 'power2.out' },
      { pinIdx: 0, scale: 1, duration: 0.8, ease: 'sine.inOut' },
    ],
  },

  // JUICIOS DE JESÚS — Jesús firme, interrogadores nerviosos, Pedro niega tres veces.
  'juicios-jesus': {
    steps: [
      { pinIdx: 0, offset: [0, 0], scale: 1, opacity: 1, duration: 0.001 },
      { pinIdx: 1, scale: 1, duration: 0.4, ease: 'sine.out' },
      { pinIdx: 2, scale: 1, duration: 0.4, ease: 'sine.out' },
      { pinIdx: 3, scale: 1, duration: 0.4, ease: 'sine.out' },
      { pinIdx: 4, offset: [10, 0], opacity: 0.6, scale: 0.9, duration: 0.001 },
      { pinIdx: 1, offset: [-3, -2], scale: 1.08, duration: 0.5, ease: 'sine.inOut' },
      { pinIdx: 1, offset: [3, 2], scale: 1.04, duration: 0.5, ease: 'sine.inOut' },
      { pinIdx: 0, scale: 1.04, duration: 0.6, ease: 'sine.inOut' },
      { pinIdx: 2, offset: [-4, 0], scale: 1.06, duration: 0.6, ease: 'sine.inOut' },
      { pinIdx: 2, offset: [4, 0], scale: 0.96, duration: 0.6, ease: 'sine.inOut' },
      { pinIdx: 4, offset: [6, 0], opacity: 0.3, scale: 0.85, duration: 0.7, ease: 'sine.inOut' },
      { pinIdx: 3, offset: [0, -3], scale: 1.05, duration: 0.5, ease: 'sine.inOut' },
      { pinIdx: 3, offset: [0, 3], scale: 0.96, duration: 0.5, ease: 'sine.inOut' },
      { pinIdx: 4, offset: [10, 0], opacity: 0.5, duration: 0.7, ease: 'sine.inOut' },
      { pinIdx: 0, scale: 1, duration: 0.5, ease: 'sine.inOut' },
      { pinIdx: 1, offset: [0, 0], scale: 1, duration: 0.7, ease: 'sine.inOut' },
      { pinIdx: 2, offset: [0, 0], scale: 1, duration: 0.7, ease: 'sine.inOut' },
      { pinIdx: 3, offset: [0, 0], scale: 1, duration: 0.7, ease: 'sine.inOut' },
      { pinIdx: 4, offset: [0, 0], scale: 1, opacity: 1, duration: 0.7, ease: 'sine.inOut' },
    ],
  },

  // MARTIRIO DE ESTEBAN — Esteban pulsa, cae bajo apedreamiento, Saulo presencia.
  'martirio-esteban': {
    steps: [
      { pinIdx: 0, offset: [0, 0], scale: 1, opacity: 1, duration: 0.001 },
      { pinIdx: 1, offset: [14, 0], scale: 0.92, opacity: 0.7, duration: 0.001 },
      { pinIdx: 0, scale: 1.18, duration: 0.7, ease: 'expo.out' },
      { pinIdx: 0, scale: 1.05, duration: 0.5, ease: 'sine.inOut' },
      { pinIdx: 0, scale: 1.2, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 1, offset: [10, 0], scale: 0.95, opacity: 0.85, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 0, offset: [0, 6], scale: 0.95, opacity: 0.85, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 0, offset: [0, 12], scale: 0.85, opacity: 0.55, duration: 1.0, ease: 'power2.in' },
      { pinIdx: 1, scale: 1, opacity: 1, duration: 0.7, ease: 'sine.inOut' },
      { pinIdx: 0, offset: [0, 18], scale: 0.7, opacity: 0.2, duration: 1.2, ease: 'expo.in' },
      { pinIdx: 0, offset: [0, 22], scale: 0.6, opacity: 0, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 1, offset: [0, 0], scale: 1, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 0, offset: [0, 0], scale: 1, opacity: 1, duration: 0.001 },
    ],
  },

  // MILAGROS DE JESÚS — pulse rítmico, discípulos atestiguan (cada milagro un beat).
  'milagros-de-jesus': {
    steps: [
      { pinIdx: 0, offset: [0, 0], scale: 1, opacity: 1, duration: 0.001 },
      { pinIdx: 1, scale: 1, duration: 0.4, ease: 'sine.out' },
      { pinIdx: 2, scale: 1, duration: 0.4, ease: 'sine.out' },
      { pinIdx: 3, scale: 1, duration: 0.4, ease: 'sine.out' },
      { pinIdx: 0, scale: 1.18, duration: 0.5, ease: 'expo.out' },
      { pinIdx: 1, scale: 1.1, duration: 0.4, ease: 'sine.out' },
      { pinIdx: 0, scale: 1, duration: 0.4, ease: 'sine.in' },
      { pinIdx: 1, scale: 1, duration: 0.4, ease: 'sine.in' },
      { pinIdx: 0, scale: 1.18, duration: 0.5, ease: 'expo.out' },
      { pinIdx: 2, scale: 1.12, duration: 0.4, ease: 'sine.out' },
      { pinIdx: 0, scale: 1, duration: 0.4, ease: 'sine.in' },
      { pinIdx: 2, scale: 1, duration: 0.4, ease: 'sine.in' },
      { pinIdx: 0, scale: 1.2, duration: 0.6, ease: 'expo.out' },
      { pinIdx: 3, scale: 1.12, duration: 0.4, ease: 'sine.out' },
      { pinIdx: 0, scale: 1, duration: 0.5, ease: 'sine.in' },
      { pinIdx: 3, scale: 1, duration: 0.5, ease: 'sine.in' },
    ],
  },

  // MUERTE DE PEDRO Y PABLO — ambos ascienden espiritualmente, opacity dim.
  'muerte-pedro-pablo': {
    steps: [
      { pinIdx: 0, offset: [0, 0], scale: 1, opacity: 1, duration: 0.001 },
      { pinIdx: 1, offset: [0, 0], scale: 1, opacity: 1, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 0, scale: 1.08, duration: 0.6, ease: 'sine.inOut' },
      { pinIdx: 1, scale: 1.08, duration: 0.6, ease: 'sine.inOut' },
      { pinIdx: 0, offset: [0, 4], scale: 0.96, opacity: 0.85, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 1, offset: [0, 4], scale: 0.96, opacity: 0.85, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 0, offset: [0, -8], scale: 0.9, opacity: 0.6, duration: 1.4, ease: 'power2.out' },
      { pinIdx: 1, offset: [0, -8], scale: 0.9, opacity: 0.6, duration: 1.4, ease: 'power2.out' },
      { pinIdx: 0, offset: [0, -22], scale: 0.78, opacity: 0.3, duration: 1.6, ease: 'expo.in' },
      { pinIdx: 1, offset: [0, -22], scale: 0.78, opacity: 0.3, duration: 1.6, ease: 'expo.in' },
      { pinIdx: 0, offset: [0, -34], scale: 0.65, opacity: 0, duration: 1.4, ease: 'sine.inOut' },
      { pinIdx: 1, offset: [0, -34], scale: 0.65, opacity: 0, duration: 1.4, ease: 'sine.inOut' },
      { pinIdx: 0, offset: [0, 0], scale: 1, opacity: 1, duration: 0.001 },
      { pinIdx: 1, offset: [0, 0], scale: 1, opacity: 1, duration: 0.001 },
    ],
  },

  // NACIMIENTO DE JESÚS — bebé emerge, padres bendicen, magos llegan.
  'nacimiento-jesus': {
    steps: [
      { pinIdx: 0, opacity: 0, scale: 0.4, duration: 0.001 },
      { pinIdx: 1, scale: 1, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 2, scale: 1, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 3, offset: [-12, 0], opacity: 0.3, scale: 0.85, duration: 0.001 },
      { pinIdx: 4, offset: [-12, 0], opacity: 0.3, scale: 0.85, duration: 0.001 },
      { pinIdx: 5, offset: [-12, 0], opacity: 0.3, scale: 0.85, duration: 0.001 },
      { pinIdx: 1, offset: [0, 3], scale: 0.97, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 0, opacity: 1, scale: 1, duration: 1.4, ease: 'expo.out' },
      { pinIdx: 0, scale: 1.15, duration: 0.7, ease: 'sine.inOut' },
      { pinIdx: 1, scale: 1.05, duration: 0.6, ease: 'sine.inOut' },
      { pinIdx: 2, scale: 1.05, duration: 0.6, ease: 'sine.inOut' },
      { pinIdx: 3, offset: [-4, 0], opacity: 0.85, scale: 0.95, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 4, offset: [-4, 0], opacity: 0.85, scale: 0.95, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 5, offset: [-4, 0], opacity: 0.85, scale: 0.95, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 3, offset: [0, 0], opacity: 1, scale: 1, duration: 0.9, ease: 'power2.out' },
      { pinIdx: 4, offset: [0, 0], opacity: 1, scale: 1, duration: 0.9, ease: 'power2.out' },
      { pinIdx: 5, offset: [0, 0], opacity: 1, scale: 1, duration: 0.9, ease: 'power2.out' },
      { pinIdx: 0, scale: 1, duration: 0.7, ease: 'sine.inOut' },
      { pinIdx: 1, offset: [0, 0], scale: 1, duration: 0.7, ease: 'sine.inOut' },
      { pinIdx: 2, scale: 1, duration: 0.7, ease: 'sine.inOut' },
    ],
  },

  // NACIMIENTO DE JUAN BAUTISTA — bebé emerge, Zacarías recupera voz, Isabel se alegra.
  'nacimiento-juan-bautista': {
    steps: [
      { pinIdx: 0, opacity: 0, scale: 0.4, duration: 0.001 },
      { pinIdx: 1, scale: 0.95, opacity: 0.7, duration: 0.001 },
      { pinIdx: 2, scale: 1, opacity: 1, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 2, offset: [0, 4], scale: 0.96, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 0, opacity: 1, scale: 1, duration: 1.4, ease: 'expo.out' },
      { pinIdx: 0, scale: 1.12, duration: 0.6, ease: 'sine.inOut' },
      { pinIdx: 2, scale: 1.05, duration: 0.6, ease: 'sine.inOut' },
      { pinIdx: 1, opacity: 1, scale: 1.15, duration: 1.0, ease: 'expo.out' },
      { pinIdx: 1, scale: 1.05, duration: 0.6, ease: 'sine.inOut' },
      { pinIdx: 0, scale: 1, duration: 0.6, ease: 'sine.inOut' },
      { pinIdx: 1, scale: 1, duration: 0.6, ease: 'sine.inOut' },
      { pinIdx: 2, offset: [0, 0], scale: 1, duration: 0.6, ease: 'sine.inOut' },
    ],
  },

  // PENTECOSTÉS — apóstoles pulsan al unísono (lenguas de fuego), Pedro se eleva como líder.
  'pentecostes': {
    steps: [
      { pinIdx: 0, offset: [0, 0], scale: 1, opacity: 1, duration: 0.001 },
      { pinIdx: 1, scale: 1, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 2, scale: 1, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 0, scale: 1.15, duration: 0.5, ease: 'expo.out' },
      { pinIdx: 1, scale: 1.15, duration: 0.5, ease: 'expo.out' },
      { pinIdx: 2, scale: 1.15, duration: 0.5, ease: 'expo.out' },
      { pinIdx: 0, scale: 1.05, duration: 0.5, ease: 'sine.inOut' },
      { pinIdx: 1, scale: 1.05, duration: 0.5, ease: 'sine.inOut' },
      { pinIdx: 2, scale: 1.05, duration: 0.5, ease: 'sine.inOut' },
      { pinIdx: 0, scale: 1.2, duration: 0.6, ease: 'expo.out' },
      { pinIdx: 1, scale: 1.12, duration: 0.6, ease: 'expo.out' },
      { pinIdx: 2, scale: 1.12, duration: 0.6, ease: 'expo.out' },
      { pinIdx: 0, offset: [0, -8], scale: 1.2, duration: 1.0, ease: 'power2.out' },
      { pinIdx: 1, scale: 1, duration: 0.7, ease: 'sine.inOut' },
      { pinIdx: 2, scale: 1, duration: 0.7, ease: 'sine.inOut' },
      { pinIdx: 0, offset: [0, 0], scale: 1, duration: 0.8, ease: 'sine.inOut' },
    ],
  },

  // PRESENTACIÓN EN EL TEMPLO — Simeón profecía (scale up + pulse), Ana también.
  'presentacion-en-el-templo': {
    steps: [
      { pinIdx: 0, offset: [0, 0], scale: 1, opacity: 1, duration: 0.001 },
      { pinIdx: 1, scale: 1, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 2, scale: 1, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 3, offset: [10, 0], opacity: 0.7, scale: 0.92, duration: 0.001 },
      { pinIdx: 4, offset: [-10, 0], opacity: 0.7, scale: 0.92, duration: 0.001 },
      { pinIdx: 0, scale: 1.1, duration: 0.7, ease: 'sine.inOut' },
      { pinIdx: 3, offset: [4, 0], opacity: 1, scale: 1.15, duration: 1.0, ease: 'expo.out' },
      { pinIdx: 3, scale: 1.05, duration: 0.5, ease: 'sine.inOut' },
      { pinIdx: 3, scale: 1.18, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 1, scale: 0.96, opacity: 0.9, duration: 0.6, ease: 'sine.inOut' },
      { pinIdx: 4, offset: [-4, 0], opacity: 1, scale: 1.12, duration: 0.9, ease: 'expo.out' },
      { pinIdx: 3, offset: [0, 0], scale: 1, duration: 0.7, ease: 'sine.inOut' },
      { pinIdx: 4, offset: [0, 0], scale: 1, duration: 0.7, ease: 'sine.inOut' },
      { pinIdx: 0, scale: 1, duration: 0.6, ease: 'sine.inOut' },
      { pinIdx: 1, scale: 1, opacity: 1, duration: 0.6, ease: 'sine.inOut' },
    ],
  },

  // RESURRECCIÓN — Jesús emerge brillante, otros asombrados (scale shrink + offset back).
  'resurreccion': {
    steps: [
      { pinIdx: 0, opacity: 0.3, scale: 0.5, duration: 0.001 },
      { pinIdx: 1, scale: 1, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 2, scale: 1, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 3, scale: 1, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 0, opacity: 0.7, scale: 0.85, duration: 1.0, ease: 'sine.out' },
      { pinIdx: 0, opacity: 1, scale: 1.25, duration: 1.2, ease: 'expo.out' },
      { pinIdx: 1, offset: [-4, 0], scale: 0.92, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 2, offset: [-4, 0], scale: 0.92, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 3, offset: [-4, 0], scale: 0.92, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 0, scale: 1.15, duration: 0.6, ease: 'sine.inOut' },
      { pinIdx: 1, offset: [-2, 0], scale: 0.96, duration: 0.6, ease: 'sine.inOut' },
      { pinIdx: 2, offset: [-2, 0], scale: 0.96, duration: 0.6, ease: 'sine.inOut' },
      { pinIdx: 3, offset: [-2, 0], scale: 0.96, duration: 0.6, ease: 'sine.inOut' },
      { pinIdx: 0, scale: 1, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 1, offset: [0, 0], scale: 1, duration: 0.7, ease: 'sine.inOut' },
      { pinIdx: 2, offset: [0, 0], scale: 1, duration: 0.7, ease: 'sine.inOut' },
      { pinIdx: 3, offset: [0, 0], scale: 1, duration: 0.7, ease: 'sine.inOut' },
    ],
  },

  // SERMÓN DEL MONTE — Jesús irradia, discípulos respiran al unísono.
  'sermon-del-monte': {
    steps: [
      { pinIdx: 0, offset: [0, 0], scale: 1, opacity: 1, duration: 0.001 },
      { pinIdx: 1, scale: 1, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 2, scale: 1, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 0, scale: 1.12, duration: 0.9, ease: 'sine.inOut' },
      { pinIdx: 1, scale: 1.04, duration: 0.9, ease: 'sine.inOut' },
      { pinIdx: 2, scale: 1.04, duration: 0.9, ease: 'sine.inOut' },
      { pinIdx: 0, scale: 1.04, duration: 0.9, ease: 'sine.inOut' },
      { pinIdx: 1, scale: 0.98, duration: 0.9, ease: 'sine.inOut' },
      { pinIdx: 2, scale: 0.98, duration: 0.9, ease: 'sine.inOut' },
      { pinIdx: 0, scale: 1.15, duration: 0.9, ease: 'sine.inOut' },
      { pinIdx: 1, scale: 1.04, duration: 0.9, ease: 'sine.inOut' },
      { pinIdx: 2, scale: 1.04, duration: 0.9, ease: 'sine.inOut' },
      { pinIdx: 0, scale: 1, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 1, scale: 1, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 2, scale: 1, duration: 0.8, ease: 'sine.inOut' },
    ],
  },

  // TENTACIONES — Satán 3 acercamientos rechazados, finalmente se aleja.
  'tentaciones-desierto': {
    steps: [
      { pinIdx: 0, offset: [0, 0], scale: 1, opacity: 1, duration: 0.001 },
      { pinIdx: 1, offset: [16, 0], opacity: 0.4, scale: 0.85, duration: 0.001 },
      { pinIdx: 0, scale: 0.96, opacity: 0.9, duration: 0.7, ease: 'sine.inOut' },
      { pinIdx: 1, offset: [6, 0], opacity: 0.8, scale: 0.95, duration: 0.9, ease: 'power2.in' },
      { pinIdx: 0, scale: 1.08, opacity: 1, duration: 0.6, ease: 'expo.out' },
      { pinIdx: 1, offset: [14, 0], opacity: 0.5, scale: 0.88, duration: 0.8, ease: 'power2.out' },
      { pinIdx: 1, offset: [4, -3], opacity: 0.85, scale: 1.05, duration: 0.9, ease: 'power2.in' },
      { pinIdx: 0, scale: 1.1, duration: 0.6, ease: 'expo.out' },
      { pinIdx: 1, offset: [16, 0], opacity: 0.45, scale: 0.85, duration: 0.8, ease: 'power2.out' },
      { pinIdx: 1, offset: [3, 3], opacity: 0.9, scale: 1.12, duration: 1.0, ease: 'power2.in' },
      { pinIdx: 0, scale: 1.15, duration: 0.6, ease: 'expo.out' },
      { pinIdx: 1, offset: [28, 4], opacity: 0.2, scale: 0.7, duration: 1.4, ease: 'expo.out' },
      { pinIdx: 1, offset: [40, 6], opacity: 0, scale: 0.55, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 0, scale: 1, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 1, offset: [0, 0], scale: 1, opacity: 1, duration: 0.001 },
    ],
  },

  // TRANSFIGURACIÓN — Jesús glow + scale, Pedro/Juan caen.
  'transfiguracion': {
    steps: [
      { pinIdx: 0, offset: [0, 0], scale: 1, opacity: 1, duration: 0.001 },
      { pinIdx: 1, scale: 1, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 2, scale: 1, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 0, scale: 1.15, duration: 0.9, ease: 'sine.inOut' },
      { pinIdx: 0, scale: 1.4, opacity: 1, duration: 1.2, ease: 'expo.out' },
      { pinIdx: 1, offset: [0, 6], scale: 0.9, opacity: 0.7, duration: 1.0, ease: 'power2.in' },
      { pinIdx: 2, offset: [0, 6], scale: 0.9, opacity: 0.7, duration: 1.0, ease: 'power2.in' },
      { pinIdx: 1, offset: [0, 10], scale: 0.82, opacity: 0.5, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 2, offset: [0, 10], scale: 0.82, opacity: 0.5, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 0, scale: 1.35, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 0, scale: 1.1, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 1, offset: [0, 4], scale: 0.95, opacity: 0.85, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 2, offset: [0, 4], scale: 0.95, opacity: 0.85, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 0, scale: 1, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 1, offset: [0, 0], scale: 1, opacity: 1, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 2, offset: [0, 0], scale: 1, opacity: 1, duration: 0.8, ease: 'sine.inOut' },
    ],
  },

  // ÚLTIMA CENA — Judas se aleja gradualmente, Jesús bendice, otros cerca.
  'ultima-cena': {
    steps: [
      { pinIdx: 0, offset: [0, 0], scale: 1, opacity: 1, duration: 0.001 },
      { pinIdx: 1, scale: 1, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 2, scale: 1, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 3, scale: 1, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 0, scale: 1.12, duration: 0.9, ease: 'sine.inOut' },
      { pinIdx: 1, scale: 1.04, duration: 0.6, ease: 'sine.inOut' },
      { pinIdx: 2, scale: 1.04, duration: 0.6, ease: 'sine.inOut' },
      { pinIdx: 0, scale: 1.18, duration: 0.7, ease: 'expo.out' },
      { pinIdx: 3, offset: [4, 0], opacity: 0.85, scale: 0.97, duration: 0.9, ease: 'sine.inOut' },
      { pinIdx: 1, scale: 1.05, duration: 0.7, ease: 'sine.inOut' },
      { pinIdx: 3, offset: [10, 0], opacity: 0.6, scale: 0.92, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 0, scale: 1.1, duration: 0.6, ease: 'sine.inOut' },
      { pinIdx: 3, offset: [18, 2], opacity: 0.25, scale: 0.85, duration: 1.2, ease: 'power2.in' },
      { pinIdx: 3, offset: [26, 4], opacity: 0, scale: 0.78, duration: 1.0, ease: 'expo.in' },
      { pinIdx: 0, scale: 1, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 1, scale: 1, duration: 0.7, ease: 'sine.inOut' },
      { pinIdx: 2, scale: 1, duration: 0.7, ease: 'sine.inOut' },
      { pinIdx: 3, offset: [0, 0], scale: 1, opacity: 1, duration: 0.001 },
    ],
  },

  // VIAJES MISIONEROS DE PABLO — drift multi-direccional, compañeros siguen.
  'viajes-misioneros-pablo': {
    steps: [
      { pinIdx: 0, offset: [0, 0], scale: 1, opacity: 1, duration: 0.001 },
      { pinIdx: 1, scale: 1, duration: 0.5, ease: 'sine.out' },
      { pinIdx: 2, scale: 1, duration: 0.5, ease: 'sine.out' },
      { pinIdx: 3, scale: 1, duration: 0.5, ease: 'sine.out' },
      { pinIdx: 0, offset: [10, -4], scale: 1.05, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 1, offset: [6, -2], scale: 0.97, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 2, offset: [4, -3], scale: 0.96, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 0, offset: [-8, 6], scale: 1.05, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 3, offset: [-4, 4], scale: 0.97, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 1, offset: [-2, 4], scale: 0.96, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 0, offset: [6, 8], scale: 1.08, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 2, offset: [4, 6], scale: 0.97, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 3, offset: [2, 6], scale: 0.96, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 0, offset: [0, 0], scale: 1, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 1, offset: [0, 0], scale: 1, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 2, offset: [0, 0], scale: 1, duration: 1.0, ease: 'sine.inOut' },
      { pinIdx: 3, offset: [0, 0], scale: 1, duration: 1.0, ease: 'sine.inOut' },
    ],
  },

  // VISITACIÓN A ISABEL — María llega, ambas pulsan, Juan salta en el vientre.
  'visitacion-isabel': {
    steps: [
      { pinIdx: 0, offset: [-14, 0], opacity: 0.6, scale: 0.92, duration: 0.001 },
      { pinIdx: 1, scale: 1, opacity: 1, duration: 0.6, ease: 'sine.out' },
      { pinIdx: 2, scale: 0.95, opacity: 0.85, duration: 0.001 },
      { pinIdx: 0, offset: [-4, 0], opacity: 1, scale: 1, duration: 1.2, ease: 'power2.out' },
      { pinIdx: 1, scale: 1.1, duration: 0.7, ease: 'sine.inOut' },
      { pinIdx: 0, offset: [0, 0], scale: 1.08, duration: 0.8, ease: 'sine.inOut' },
      { pinIdx: 1, scale: 1.15, duration: 0.7, ease: 'expo.out' },
      { pinIdx: 2, scale: 1.18, opacity: 1, duration: 0.6, ease: 'expo.out' },
      { pinIdx: 2, scale: 0.95, duration: 0.5, ease: 'sine.inOut' },
      { pinIdx: 2, scale: 1.15, duration: 0.5, ease: 'expo.out' },
      { pinIdx: 0, scale: 1.1, duration: 0.6, ease: 'sine.inOut' },
      { pinIdx: 1, scale: 1.08, duration: 0.6, ease: 'sine.inOut' },
      { pinIdx: 2, scale: 1, duration: 0.5, ease: 'sine.inOut' },
      { pinIdx: 0, scale: 1, duration: 0.7, ease: 'sine.inOut' },
      { pinIdx: 1, scale: 1, duration: 0.7, ease: 'sine.inOut' },
    ],
  },
};

export default EVANGELIO;
